### ISSUE TITLE
serverless-webpack Plugin Removes Handler Helper Module

### ISSUE THREAD

**Issue by kolanos** [iopipe/serverless-iopipe-layers#19]
When using the plugin in combination with the serverless-webpack plugin there is no way to ensure that the handler helper is included in the package.

**Comment by Zurnaz** [comment]
Not sure if this will help but while I was debugging I noticed that when I tweaked the webpack config to merge the entry points to include the wrapper. Like so: 
https://gist.github.com/Zurnaz/52ece504cf75a37503eae8b5edd59c93

It ended up not including my lambda src files in the webpack build.

I noticed the wrapper just included a module exports so i created my own that had a dash instead of an underscore and replaced the generated one in the webpack config

This created a build with the correct wrapper and the src files included but when deployed there was an error on the lambda that it was unable to import the module that was my lambda.
https://gist.github.com/Zurnaz/08ae3e8aaea3739cf2220a779b9643e4

At that point I gave up and used the other non layers serverless plugin which worked.

**Comment by ewindisch** [comment]
We should simply map to the in-layer handler when using Node 10.x

**Comment by kolanos** [comment]
@Zurnaz Thanks for the notes. Working on a fix.

**Comment by kolanos** [comment]
> This created a build with the correct wrapper and the src files included but when deployed there was an error on the lambda that it was unable to import the module that was my lambda. 

This is likely a result of serverless-webpack also overriding the `handdler` with the webpack build artifact. The IOpipe plugin will need to come after serverless-webpack in the `plugins` order in order to make sure it's mapping the correct `handler` target.
